server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

couchbase:
    cluster:
        bucket: default
        ip: 127.0.0.1
        #ip: 52.11.168.82
        password: password

mail:
    host: smtp.gmail.com
    port: 587
    username: paul@mefford.org
    password: khammanivong
    protocol: smtp
    tls: true
    auth: true
    from: paul@mefford.org
    debug: true


metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: patientfocus


report:
    url: http://localhost:8080/#/report/
